
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Interpretador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR_SOMA = 13;
  public static final int LETRA = 4;
  public static final int SEPARADOR_FECHA_COLCHETE = 21;
  public static final int SEPARADOR_FECHA_PARENTESE = 19;
  public static final int RELACIONAL_MENOR = 16;
  public static final int PALAVRA = 5;
  public static final int OPERADOR_SUBTRACAO = 14;
  public static final int SEPARADOR_ABRE_PARENTESE = 18;
  public static final int SIMBOLO_ORDINAL = 17;
  public static final int ATRIBUICAO = 10;
  public static final int SEPARADOR = 23;
  public static final int STRING = 6;
  public static final int EOF = 0;
  public static final int DIGITO = 2;
  public static final int REPETICAO = 9;
  public static final int error = 1;
  public static final int NUMERO = 3;
  public static final int CONDICIONAL_SE = 11;
  public static final int CONDICIONAL_SENAO = 12;
  public static final int DELIMITADOR = 22;
  public static final int VARIAVEL = 7;
  public static final int SEPARADOR_ABRE_COLCHETE = 20;
  public static final int LISTA = 8;
  public static final int RELACIONAL_MAIOR = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIGITO",
  "NUMERO",
  "LETRA",
  "PALAVRA",
  "STRING",
  "VARIAVEL",
  "LISTA",
  "REPETICAO",
  "ATRIBUICAO",
  "CONDICIONAL_SE",
  "CONDICIONAL_SENAO",
  "OPERADOR_SOMA",
  "OPERADOR_SUBTRACAO",
  "RELACIONAL_MAIOR",
  "RELACIONAL_MENOR",
  "SIMBOLO_ORDINAL",
  "SEPARADOR_ABRE_PARENTESE",
  "SEPARADOR_FECHA_PARENTESE",
  "SEPARADOR_ABRE_COLCHETE",
  "SEPARADOR_FECHA_COLCHETE",
  "DELIMITADOR",
  "SEPARADOR"
  };
}

